name: F5 and NRFI/YRFI
on: 
  workflow_dispatch:
  push:
    paths:
      - 'F5AndNRFI.py'
      - '.github/workflows/F5AndNRFI.yml'

#  schedule:
#    - cron: '0 11,16 * * *'
permissions: write-all

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout relevant files  
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            F5AndNRFI.py
            Outputs/F5.png
            Outputs/NRFIs.png
            Outputs/nrfi_yrfi_picks.csv
            Outputs/f5_chart.csv
          sparse-checkout-cone-mode: false
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.9'      
      - name: Run script
        run: |
          pip install --upgrade pip
          pip install requests
          pip install bs4
          pip install pandas
          pip install matplotlib
          pip install numpy
          pip install datetime
          pip install selenium
          pip install lxml
          pip install html5lib
          python F5AndNRFI.py
          git config --global user.email "benaharon1@yahoo.com"
          git config --global user.name "bena618"
          git pull

          git add . || true
          if ! git diff --cached --quiet; then
            git commit -m "Workflow updating NRFIs.png, F5.png, nrfi_yrfi_picks.csv, and f5_chart.csv"
            git push
          else
            echo "No changes to commit in MLB_Models"
          fi

      - name: Clone BBSFrontend repo
        env:
          BBSFRONTEND_TOKEN: ${{ secrets.BBSFRONTEND_TOKEN }}
        run: |
          git clone https://x-access-token:${BBSFRONTEND_TOKEN}@github.com/bena618/BBSFrontend.git

      - name: Copy updated CSV to BBSFrontend
        run: |
          cp Outputs/nrfi_yrfi_picks.csv BBSFrontend/model_outputs/nrfi_yrfi_picks.csv
          cp Outputs/f5_picks.csv BBSFrontend/model_outputs/f5_chart.csv

      - name: Move into clone
        run: |
          cd BBSFrontend

      - name: Commit and push changes to BBSFrontend
        working-directory: BBSFrontend
        run: |
          git add model_outputs/nrfi_yrfi_picks.csv
          if ! git diff --cached --quiet; then
            git commit -m "Update nrfi_yrfi_picks.csv and f5_chart.csv from MLB_Models workflow"
            git push
          else
            echo "No changes to commit in BBSFrontend"
          fi
