name: Hits
on: 
  workflow_dispatch:
  push:
    paths:
      - 'Hits.py'
      - '.github/workflows/Hits.yml'

permissions: write-all

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout relevant files  
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Hits.py
            Outputs/LeastLikelyHit.png
            Outputs/MostHits.png
            Outputs/MostLikelyHit.png
            Outputs/MostLikelyHitAdj.png
            Outputs/hits_chart.csv
          sparse-checkout-cone-mode: false
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.9'      
      - name: Run script
        run: |
          pip install --upgrade pip
          pip install requests
          pip install bs4
          pip install pandas
          pip install matplotlib
          pip install numpy
          pip install datetime
          pip install selenium
          pip install lxml
          pip install html5lib
          pip install scikit-learn
          python Hits.py
          git config --global user.email "benaharon1@yahoo.com"
          git config --global user.name "bena618"
          git pull
          git add . || true
          if ! git diff --cached --quiet; then
            git commit -m "Workflow updating LeastLikelyHit.png, MostHits.png, MostLikelyHit.png, MostLikelyHitAdj.png, and hits_chart.csv"
            git push
          else
            echo "No changes to commit in MLB_Models"
          fi

      - name: Clone BBSFrontend repo
        env:
          BBSFRONTEND_TOKEN: ${{ secrets.BBSFRONTEND_TOKEN }}
        run: |
          git clone https://x-access-token:${BBSFRONTEND_TOKEN}@github.com/bena618/BBSFrontend.git

      - name: Copy updated CSV to BBSFrontend
        run: |
          cp Outputs/hits_chart.csv BBSFrontend/model_outputs/hit_picks.csv

      - name: Move into clone
        run: |
          cd BBSFrontend

      - name: Commit and push changes to BBSFrontend
        working-directory: BBSFrontend
        run: |
          git add model_outputs/hit_picks.csv
          if ! git diff --cached --quiet; then
            git commit -m "Update hit_picks.csv from MLB_Models workflow"
            git push
          else
            echo "No changes to commit in BBSFrontend"
          fi