name: Ks
on: 
  workflow_dispatch:
  push:
    paths:
      - 'Ks.py'
      - '.github/workflows/Ks.yml'

#  schedule:
#    - cron: '0 11,16 * * *'
permissions: write-all

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository  
        uses: actions/checkout@v2
      - name: Checkout relevant files  
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Ks.py
            Outputs/Ks.png
            Outputs/strikeout_preds.csv
          sparse-checkout-cone-mode: false
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.9'      
      - name: Run script
        run: |
          pip install --upgrade pip
          pip install requests
          pip install bs4
          pip install pandas
          pip install matplotlib
          pip install numpy
          pip install datetime
          pip install selenium
          pip install lxml
          pip install html5lib
          pip install scikit-learn
          python Ks.py
          git config --global user.email "benaharon1@yahoo.com"
          git config --global user.name "bena618"
          git pull

          git add . || true
          if ! git diff --cached --quiet; then
            git commit -m "Workflow updating Ks.png and strikeout_preds.csv"
            git push
          else
            echo "No changes to commit in MLB_Models"
          fi

      # - name: Clone BBSFrontend repo
      #   env:
      #     BBSFRONTEND_TOKEN: ${{ secrets.BBSFRONTEND_TOKEN }}
      #   run: |
      #     git clone https://x-access-token:${BBSFRONTEND_TOKEN}@github.com/bena618/BBSFrontend.git

      # - name: Copy updated CSV to BBSFrontend
      #   run: |
      #     cp Outputs/strikeout_preds.csv BBSFrontend/model_outputs/strikeout_preds.csv

      # - name: Move into clone
      #   run: |
      #     cd BBSFrontend

      # - name: Commit and push changes to BBSFrontend
      #   working-directory: BBSFrontend
      #   run: |
      #     git add model_outputs/strikeout_preds.csv
      #     if ! git diff --cached --quiet; then
      #       git commit -m "Update strikeout_preds.csv from MLB_Models workflow"
      #       git push
      #     else
      #       echo "No changes to commit in BBSFrontend"
      #     fi
