name: 1st Inning Score Predictor Roto
on: 
  workflow_dispatch:
  push:
    paths:
      - 'withRotoIdea.py'
      - '.github/workflows/withRotoIdea.yml'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository  
        uses: actions/checkout@v2
      - name: Checkout relevant files  
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            withRotoIdea.py
          sparse-checkout-cone-mode: false
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.9'      
      - name: Run script
        run: |
          pip install --upgrade pip
          pip install requests
          pip install bs4
          pip install requests
          pip install selenium
          pip install pandas
          pip install matplotlib
          python withRotoIdea.py
